name: Go + PostgreSQL

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          stable: 'false'
          go-version: '1.25.1'

      - name: Publish Docker Image
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          IMAGE_NAME: gopost
        run: |
          cd ch05
          docker images
          docker build -t "$IMAGE_NAME" .
          docker images
          echo "$PASSWORD" | docker login --username "$USERNAME" --password-stdin
          docker tag "${IMAGE_NAME}" "$USERNAME/${IMAGE_NAME}:latest"
          docker push "$USERNAME/${IMAGE_NAME}:latest"
          echo "* Running Docker Image"
          docker run ${IMAGE_NAME}:latest